version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartspenddb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "9090:80"
    depends_on:
      - db
    volumes:
      - ./PFS:/var/www/html

volumes:
  db_data:
