version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-container
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_DATABASE: smartspenddb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_volume:/var/lib/mysql

volumes:
  database_volume:
